theme: jekyll-theme-minimal
title: Identification précise des variants microbiens (ASVs) avec DADA2
description: Dans ce projet, je réanalyse des données de séquençage 16S MiSeq provenant du microbiote de souris. J'utilise le pipeline DADA2 pour nettoyer les séquences, corriger les erreurs et conserver uniquement les vraies variantes bactériennes (ASVs). Ensuite, j'identifie leur taxonomie grâce à la base SILVA. Enfin, avec Phyloseq, j'étudis la diversité des bactéries et comparons la composition du microbiote au début et à la fin de l’expérience. Travail réalisé par Nawel Zaidi.


# Markdown & code
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# (optionnel) Réseaux sociaux affichés par le thème
github:
  is_project_page: false